### ISSUE TITLE
 [ERR_PACKAGE_PATH_NOT_EXPORTED]: Package subpath './package.json' is not defined by "exports" in /home/react-storefront/node_modules/react/package.json

### ISSUE THREAD

**Issue by buzzeins** [saleor/react-storefront#142]
### Summary

Just got: ERR_PACKAGE_PATH_NOT_EXPORTED

```
ready - started server on 0.0.0.0:3001, url: http://localhost:3001
info  - Loaded env from /home/react-storefront/.env
Error [ERR_PACKAGE_PATH_NOT_EXPORTED]: Package subpath './package.json' is not defined by "exports" in /home/react-storefront/node_modules/react/package.json
    at new NodeError (node:internal/errors:371:5)
    at throwExportsNotFound (node:internal/modules/esm/resolve:429:9)
    at packageExportsResolve (node:internal/modules/esm/resolve:705:3)
    at resolveExports (node:internal/modules/cjs/loader:482:36)
    at Function.Module._findPath (node:internal/modules/cjs/loader:522:31)
    at Function.Module._resolveFilename (node:internal/modules/cjs/loader:919:27)
    at Function.mod._resolveFilename (/home/react-storefront/node_modules/.pnpm/next@12.0.10_757a802188413a36d4f24237d13b8e90/node_modules/next/dist/build/webpack/require-hook.js:183:28)
    at Function.resolve (node:internal/modules/cjs/helpers:108:19)
    at getPackagePath (/home/react-storefront/node_modules/.pnpm/next@12.0.10_757a802188413a36d4f24237d13b8e90/node_modules/next/dist/build/webpack-config.js:548:41)
    at Object.getBaseWebpackConfig [as default] (/home/react-storefront/node_modules/.pnpm/next@12.0.10_757a802188413a36d4f24237d13b8e90/node_modules/next/dist/build/webpack-config.js:564:9) {
  code: 'ERR_PACKAGE_PATH_NOT_EXPORTED'
}
 ELIFECYCLE  Command failed with exit code 1.
```

### Steps to reproduce

git clone git@github.com:saleor/react-storefront.git
pnpm i
npm run dev

node -v --> v17.5.0

### What OS are you using?

Linux

### Your `next.config.js` file

```
const withBundleAnalyzer = require("@next/bundle-analyzer")({
  enabled: process.env.ANALYZE === "true",
});

module.exports = withBundleAnalyzer({
  reactStrictMode: true,
  // swcMinify: true,
  swcMinify: false,
  images: {
    domains: ["vercel.saleor.cloud", "img.youtube.com"],
    formats: ["image/avif", "image/webp"],
  },
  async redirects() {
    return [
      {
        source: "/",
        // TODO: Investigate why constants from project cannot be imported
        // User should be redirected to the defaults defined in @lib/regions
        destination: "/default-channel/en-US",
        permanent: false,
      },
    ];
  },
});
```

### Builds logs (or link to your logs)

<details>
  <summary>Build logs</summary>

```
# Paste logs here
```

</details>

### Function logs

<details>
  <summary>Function logs</summary>

```
Error [ERR_PACKAGE_PATH_NOT_EXPORTED]: Package subpath './package.json' is not defined by "exports" in /home/react-storefront/node_modules/react/package.json
    at new NodeError (node:internal/errors:371:5)
    at throwExportsNotFound (node:internal/modules/esm/resolve:429:9)
    at packageExportsResolve (node:internal/modules/esm/resolve:705:3)
    at resolveExports (node:internal/modules/cjs/loader:482:36)
    at Function.Module._findPath (node:internal/modules/cjs/loader:522:31)
    at Function.Module._resolveFilename (node:internal/modules/cjs/loader:919:27)
    at Function.mod._resolveFilename (/home/react-storefront/node_modules/.pnpm/next@12.0.10_757a802188413a36d4f24237d13b8e90/node_modules/next/dist/build/webpack/require-hook.js:183:28)
    at Function.resolve (node:internal/modules/cjs/helpers:108:19)
    at getPackagePath (/home/react-storefront/node_modules/.pnpm/next@12.0.10_757a802188413a36d4f24237d13b8e90/node_modules/next/dist/build/webpack-config.js:548:41)
    at Object.getBaseWebpackConfig [as default] (/home/react-storefront/node_modules/.pnpm/next@12.0.10_757a802188413a36d4f24237d13b8e90/node_modules/next/dist/build/webpack-config.js:564:9) {
  code: 'ERR_PACKAGE_PATH_NOT_EXPORTED'
}
 ELIFECYCLE  Command failed with exit code 1.
```

</details>

**Comment by jamalbendadi** [comment]
I think using node ^16 solves the problem, what you also can do with node 17 is go to this file /home/react-storefront/node_modules/react/package.json and replace "./" in the exports subsection with "./package.json"

**Comment by zaiste** [comment]
Yes, as described by @jamalbendadi you should be using a Node.js LTS version e.g. `16`.
