### ISSUE TITLE
pnpm run generate fails out of the box

### ISSUE THREAD

**Issue by matteius** [saleor/react-storefront#207]
### Summary

I am trying to fix the prior issue I reported and finding that without making any changes I am unable to successfully run `pnpm run generate`.

### Steps to reproduce

Checkout latest `react-storefront`  
Modify Dockerfile to use `RUN npm install -g pnpm@6.32.11` since the head of pnpm fails.
Ensure using `npm install -g pnpm@6.32.11`
Now run `pnpm run generate` to try and process the thing, but it fails.

### A link to a reproduction repository

https://github.com/matteius/react-storefront

### What OS are you using?

Linux

### Your `next.config.js` file

<details>
  <summary>`next.config.js`</summary>

```
const withBundleAnalyzer = require("@next/bundle-analyzer")({
  enabled: process.env.ANALYZE === "true",
});

const apiURL = new URL(process.env.NEXT_PUBLIC_API_URI);
const allowedImageDomains = process.env.NEXT_PUBLIC_ALLOWED_IMAGE_DOMAINS
  ? process.env.NEXT_PUBLIC_ALLOWED_IMAGE_DOMAINS.split(",")
  : [];
const imageConversionFormats = process.env.NEXT_PUBLIC_IMAGE_CONVERSION_FORMATS
  ? process.env.NEXT_PUBLIC_IMAGE_CONVERSION_FORMATS.split(",")
  : [];

module.exports = withBundleAnalyzer({
  reactStrictMode: true,
  swcMinify: true,
  images: {
    domains: [apiURL.hostname, ...allowedImageDomains],
    formats: imageConversionFormats,
  },
  async headers() {
    return [
      {
        source: "/(.*)",
        headers: [
          {
            key: "x-content-type-options",
            value: "nosniff",
          },
          { key: "x-xss-protection", value: "1" },
          { key: "x-frame-options", value: "DENY" },
          {
            key: "strict-transport-security",
            value: "max-age=31536000; includeSubDomains",
          },
        ],
      },
    ];
  },
  experimental: {
    reactRoot: true,
  },
});
```

</details>

### Builds logs (or link to your logs)

<details>
  <summary>Build logs</summary>

```
(saleor) matteius@matteius-VirtualBox:~/mattscoinage/react-storefront$ pnpm run generate

> react-storefront@0.1.0 generate /home/matteius/mattscoinage/react-storefront
> dotenv -c -- graphql-codegen --config codegen.yml -w

  ✔ Parse configuration
  ❯ Generate outputs
    ❯ Generate saleor/api.tsx
      ✔ Load GraphQL schemas
      ✔ Load GraphQL documents
      ✖ Generate
        →     at /home/matteius/mattscoinage/react-storefront/graphql/mutations/CheckoutLineUpdate.graphql:6:45
    ❯ Generate ./graphql.schema.json
      ✔ Load GraphQL schemas
      ✔ Load GraphQL documents
      ✖ Generate
        →     at /home/matteius/mattscoinage/react-storefront/graphql/mutations/CheckoutLineUpdate.graphql:6:45


 Found 2 errors

  ✖ saleor/api.tsx
    AggregateError: GraphQL Document Validation failed with 1 errors;
      Error 0: GraphQLDocumentError: Variable "$lines" of type "[CheckoutLineInput!]!" used in position expecting type "[CheckoutLineUpdateInput!]!".
        at /home/matteius/mattscoinage/react-storefront/graphql/mutations/CheckoutLineUpdate.graphql:3:3
        at /home/matteius/mattscoinage/react-storefront/graphql/mutations/CheckoutLineUpdate.graphql:6:45
        at new exports.AggregateError (/home/matteius/mattscoinage/react-storefront/node_modules/.pnpm/@graphql-tools+utils@8.6.1_graphql@16.3.0/node_modules/@graphql-tools/utils/index.js:82:16)
        at Object.checkValidationErrors (/home/matteius/mattscoinage/react-storefront/node_modules/.pnpm/@graphql-tools+utils@8.6.1_graphql@16.3.0/node_modules/@graphql-tools/utils/index.js:1253:15)
        at Object.codegen (/home/matteius/mattscoinage/react-storefront/node_modules/.pnpm/@graphql-codegen+core@2.5.1_graphql@16.3.0/node_modules/@graphql-codegen/core/index.js:175:15)
        at async process (/home/matteius/mattscoinage/react-storefront/node_modules/.pnpm/@graphql-codegen+cli@2.6.2_graphql@16.3.0+typescript@4.6.3/node_modules/@graphql-codegen/cli/bin.js:1126:56)
        at async Promise.all (index 0)
        at async /home/matteius/mattscoinage/react-storefront/node_modules/.pnpm/@graphql-codegen+cli@2.6.2_graphql@16.3.0+typescript@4.6.3/node_modules/@graphql-codegen/cli/bin.js:1136:37
        at async /home/matteius/mattscoinage/react-storefront/node_modules/.pnpm/@graphql-codegen+cli@2.6.2_graphql@16.3.0+typescript@4.6.3/node_modules/@graphql-codegen/cli/bin.js:925:21
    AggregateError: GraphQL Document Validation failed with 1 errors;
      Error 0: GraphQLDocumentError: Variable "$lines" of type "[CheckoutLineInput!]!" used in position expecting type "[CheckoutLineUpdateInput!]!".
        at /home/matteius/mattscoinage/react-storefront/graphql/mutations/CheckoutLineUpdate.graphql:3:3
        at /home/matteius/mattscoinage/react-storefront/graphql/mutations/CheckoutLineUpdate.graphql:6:45
        at new exports.AggregateError (/home/matteius/mattscoinage/react-storefront/node_modules/.pnpm/@graphql-tools+utils@8.6.1_graphql@16.3.0/node_modules/@graphql-tools/utils/index.js:82:16)
        at Object.checkValidationErrors (/home/matteius/mattscoinage/react-storefront/node_modules/.pnpm/@graphql-tools+utils@8.6.1_graphql@16.3.0/node_modules/@graphql-tools/utils/index.js:1253:15)
        at Object.codegen (/home/matteius/mattscoinage/react-storefront/node_modules/.pnpm/@graphql-codegen+core@2.5.1_graphql@16.3.0/node_modules/@graphql-codegen/core/index.js:175:15)
        at async process (/home/matteius/mattscoinage/react-storefront/node_modules/.pnpm/@graphql-codegen+cli@2.6.2_graphql@16.3.0+typescript@4.6.3/node_modules/@graphql-codegen/cli/bin.js:1126:56)
        at async Promise.all (index 0)
        at async /home/matteius/mattscoinage/react-storefront/node_modules/.pnpm/@graphql-codegen+cli@2.6.2_graphql@16.3.0+typescript@4.6.3/node_modules/@graphql-codegen/cli/bin.js:1136:37
        at async /home/matteius/mattscoinage/react-storefront/node_modules/.pnpm/@graphql-codegen+cli@2.6.2_graphql@16.3.0+typescript@4.6.3/node_modules/@graphql-codegen/cli/bin.js:925:21

  ✖ ./graphql.schema.json
    AggregateError: GraphQL Document Validation failed with 1 errors;
      Error 0: GraphQLDocumentError: Variable "$lines" of type "[CheckoutLineInput!]!" used in position expecting type "[CheckoutLineUpdateInput!]!".
        at /home/matteius/mattscoinage/react-storefront/graphql/mutations/CheckoutLineUpdate.graphql:3:3
        at /home/matteius/mattscoinage/react-storefront/graphql/mutations/CheckoutLineUpdate.graphql:6:45
        at new exports.AggregateError (/home/matteius/mattscoinage/react-storefront/node_modules/.pnpm/@graphql-tools+utils@8.6.1_graphql@16.3.0/node_modules/@graphql-tools/utils/index.js:82:16)
        at Object.checkValidationErrors (/home/matteius/mattscoinage/react-storefront/node_modules/.pnpm/@graphql-tools+utils@8.6.1_graphql@16.3.0/node_modules/@graphql-tools/utils/index.js:1253:15)
        at Object.codegen (/home/matteius/mattscoinage/react-storefront/node_modules/.pnpm/@graphql-codegen+core@2.5.1_graphql@16.3.0/node_modules/@graphql-codegen/core/index.js:175:15)
        at async process (/home/matteius/mattscoinage/react-storefront/node_modules/.pnpm/@graphql-codegen+cli@2.6.2_graphql@16.3.0+typescript@4.6.3/node_modules/@graphql-codegen/cli/bin.js:1126:56)
        at async Promise.all (index 0)
        at async /home/matteius/mattscoinage/react-storefront/node_modules/.pnpm/@graphql-codegen+cli@2.6.2_graphql@16.3.0+typescript@4.6.3/node_modules/@graphql-codegen/cli/bin.js:1136:37
        at async /home/matteius/mattscoinage/react-storefront/node_modules/.pnpm/@graphql-codegen+cli@2.6.2_graphql@16.3.0+typescript@4.6.3/node_modules/@graphql-codegen/cli/bin.js:925:21
    AggregateError: GraphQL Document Validation failed with 1 errors;
      Error 0: GraphQLDocumentError: Variable "$lines" of type "[CheckoutLineInput!]!" used in position expecting type "[CheckoutLineUpdateInput!]!".
        at /home/matteius/mattscoinage/react-storefront/graphql/mutations/CheckoutLineUpdate.graphql:3:3
        at /home/matteius/mattscoinage/react-storefront/graphql/mutations/CheckoutLineUpdate.graphql:6:45
        at new exports.AggregateError (/home/matteius/mattscoinage/react-storefront/node_modules/.pnpm/@graphql-tools+utils@8.6.1_graphql@16.3.0/node_modules/@graphql-tools/utils/index.js:82:16)
        at Object.checkValidationErrors (/home/matteius/mattscoinage/react-storefront/node_modules/.pnpm/@graphql-tools+utils@8.6.1_graphql@16.3.0/node_modules/@graphql-tools/utils/index.js:1253:15)
        at Object.codegen (/home/matteius/mattscoinage/react-storefront/node_modules/.pnpm/@graphql-codegen+core@2.5.1_graphql@16.3.0/node_modules/@graphql-codegen/core/index.js:175:15)
        at async process (/home/matteius/mattscoinage/react-storefront/node_modules/.pnpm/@graphql-codegen+cli@2.6.2_graphql@16.3.0+typescript@4.6.3/node_modules/@graphql-codegen/cli/bin.js:1126:56)
        at async Promise.all (index 0)
        at async /home/matteius/mattscoinage/react-storefront/node_modules/.pnpm/@graphql-codegen+cli@2.6.2_graphql@16.3.0+typescript@4.6.3/node_modules/@graphql-codegen/cli/bin.js:1136:37
        at async /home/matteius/mattscoinage/react-storefront/node_modules/.pnpm/@graphql-codegen+cli@2.6.2_graphql@16.3.0+typescript@4.6.3/node_modules/@graphql-codegen/cli/bin.js:925:21


  ℹ Watching for changes...
^C  Shutting down watch...
```

</details>

**Comment by matteius** [comment]
Ok I have fixed this in my fork:  https://github.com/matteius/react-storefront

But probably you'll want to port what is relevant because I also changed the default country from PL to US and I am going to start customizing the site more for my use case.   Will be interesting to see how to port back in the upstream changes, but I am fairly set in using this product since its Python/Django backend is what I am most trained in, and I have some react next.js experience.  It was actually kind-of fun figuring this out because it was my first time tinkering with TypeScript directly.

**Comment by RyanTamulevicz** [comment]
> Ok I have fixed this in my fork: https://github.com/matteius/react-storefront
> 
> But probably you'll want to port what is relevant because I also changed the default country from PL to US and I am going to start customizing the site more for my use case. Will be interesting to see how to port back in the upstream changes, but I am fairly set in using this product since its Python/Django backend is what I am most trained in, and I have some react next.js experience. It was actually kind-of fun figuring this out because it was my first time tinkering with TypeScript directly.

What was the fix for this? @matteius

**Comment by krzysztofwolski** [comment]
The main branch has been updated with a fix. Thank you for the report!
