### ISSUE TITLE
Error when connecting the storefront with saleor in a local environment

### ISSUE THREAD

**Issue by dotwilliamrc** [saleor/react-storefront#728]
### Summary

# Error

I installed saleor manually on my computer. saleor and the dashboard work perfectly. but the store does not connect to graphql when running it I get the following error

## Browser Output
```
Server Error

Error: request to http://localhost:8000/graphql/ failed, reason: connect ECONNREFUSED ::1:8000
This error happened while generating the page. Any console logs will be displayed in the terminal window.
Call Stack
<unknown>
error: request to http://localhost:8000/graphql/ failed, reason: connect ECONNREFUSED : (1:8000)
<unknown> (Error: request to
http://localhost:8000/graphql/%20failed,%20reason:%20connect%20ECONNREFUSED%20: (1:8000)
new ApolloError
file:/home/dotwilliamrc/workspace/saleor/saleorr/react-storefront/node_modules/.pnpm/registry.npmjs.org+@apollo+client@3.7.1_gdcq4dv6opitr3wbfwyjmanyra/node_modules/@apollo/client/errors/errors.cjs (34:28)
<unknown>
file:/home/dotwilliamrc/workspace/saleor/saleorr/react-storefront/node_modules/.pnpm/registry.npmjs.org+@apollo+client@3.7.1_gdcq4dv6opitr3wbfwyjmanyra/node_modules/@apollo/client/core/core.cjs (1698:19)
both
file:/home/dotwilliamrc/workspace/saleor/saleorr/react-storefront/node_modules/.pnpm/registry.npmjs.org+@apollo+client@3.7.1_gdcq4dv6opitr3wbfwyjmanyra/node_modules/@apollo/client/utilities/utilities.cjs (997:53)
<unknown>
file:/home/dotwilliamrc/workspace/saleor/saleorr/react-storefront/node_modules/.pnpm/registry.npmjs.org+@apollo+client@3.7.1_gdcq4dv6opitr3wbfwyjmanyra/node_modules/@apollo/client/utilities/utilities.cjs (990:72)
new Promise
<anonymous>
Object.then
file:/home/dotwilliamrc/workspace/saleor/saleorr/react-storefront/node_modules/.pnpm/registry.npmjs.org+@apollo+client@3.7.1_gdcq4dv6opitr3wbfwyjmanyra/node_modules/@apollo/client/utilities/utilities.cjs (990:24)
Object.error
file:/home/dotwilliamrc/workspace/saleor/saleorr/react-storefront/node_modules/.pnpm/registry.npmjs.org+@apollo+client@3.7.1_gdcq4dv6opitr3wbfwyjmanyra/node_modules/@apollo/client/utilities/utilities.cjs (998:49)
notifySubscription
file:/home/dotwilliamrc/workspace/saleor/saleorr/react-storefront/node_modules/.pnpm/registry.npmjs.org+zen-observable@0.8.15/node_modules/zen-observable/lib/Observable.js (140:18)
onNotify
file:/home/dotwilliamrc/workspace/saleor/saleorr/react-storefront/node_modules/.pnpm/registry.npmjs.org+zen-observable@0.8.15/node_modules/zen-observable/lib/Observable.js (179:3)
SubscriptionObserver.error
file:/home/dotwilliamrc/workspace/saleor/saleorr/react-storefront/node_modules/.pnpm/registry.npmjs.org+zen-observable@0.8.15/node_modules/zen-observable/lib/Observable.js (240:7)
```

## Shell output

```
saleor-app-checkout:dev: event - compiled client and server successfully in 570 ms (1354 modules)
storefront:dev: error - ApolloError: request to http://localhost:8000/graphql/ failed, reason: connect ECONNREFUSED ::1:8000
storefront:dev:     at new ApolloError (/home/dotwilliamrc/workspace/saleor/saleorr/react-storefront/node_modules/.pnpm/registry.npmjs.org+@apollo+client@3.7.1_gdcq4dv6opitr3wbfwyjmanyra/node_modules/@apollo/client/errors/errors.cjs:34:28)
storefront:dev:     at /home/dotwilliamrc/workspace/saleor/saleorr/react-storefront/node_modules/.pnpm/registry.npmjs.org+@apollo+client@3.7.1_gdcq4dv6opitr3wbfwyjmanyra/node_modules/@apollo/client/core/core.cjs:1698:19
storefront:dev:     at both (/home/dotwilliamrc/workspace/saleor/saleorr/react-storefront/node_modules/.pnpm/registry.npmjs.org+@apollo+client@3.7.1_gdcq4dv6opitr3wbfwyjmanyra/node_modules/@apollo/client/utilities/utilities.cjs:997:53)
storefront:dev:     at /home/dotwilliamrc/workspace/saleor/saleorr/react-storefront/node_modules/.pnpm/registry.npmjs.org+@apollo+client@3.7.1_gdcq4dv6opitr3wbfwyjmanyra/node_modules/@apollo/client/utilities/utilities.cjs:990:72
storefront:dev:     at new Promise (<anonymous>)
storefront:dev:     at Object.then (/home/dotwilliamrc/workspace/saleor/saleorr/react-storefront/node_modules/.pnpm/registry.npmjs.org+@apollo+client@3.7.1_gdcq4dv6opitr3wbfwyjmanyra/node_modules/@apollo/client/utilities/utilities.cjs:990:24)
storefront:dev:     at Object.error (/home/dotwilliamrc/workspace/saleor/saleorr/react-storefront/node_modules/.pnpm/registry.npmjs.org+@apollo+client@3.7.1_gdcq4dv6opitr3wbfwyjmanyra/node_modules/@apollo/client/utilities/utilities.cjs:998:49)
storefront:dev:     at notifySubscription (/home/dotwilliamrc/workspace/saleor/saleorr/react-storefront/node_modules/.pnpm/registry.npmjs.org+zen-observable@0.8.15/node_modules/zen-observable/lib/Observable.js:140:18)
storefront:dev:     at onNotify (/home/dotwilliamrc/workspace/saleor/saleorr/react-storefront/node_modules/.pnpm/registry.npmjs.org+zen-observable@0.8.15/node_modules/zen-observable/lib/Observable.js:179:3)
storefront:dev:     at SubscriptionObserver.error (/home/dotwilliamrc/workspace/saleor/saleorr/react-storefront/node_modules/.pnpm/registry.npmjs.org+zen-observable@0.8.15/node_modules/zen-observable/lib/Observable.js:240:7) {
storefront:dev:   graphQLErrors: [],
storefront:dev:   clientErrors: [],
storefront:dev:   networkError: FetchError: request to http://localhost:8000/graphql/ failed, reason: connect ECONNREFUSED ::1:8000
storefront:dev:       at ClientRequest.<anonymous> (/home/dotwilliamrc/workspace/saleor/saleorr/react-storefront/node_modules/.pnpm/registry.npmjs.org+next@13.0.4_672uxklweod7ene3nqtsh262ca/node_modules/next/dist/compiled/node-fetch/index.js:1:65756)
storefront:dev:       at ClientRequest.emit (node:events:513:28)
storefront:dev:       at Socket.socketErrorListener (node:_http_client:496:9)
storefront:dev:       at Socket.emit (node:events:513:28)
storefront:dev:       at emitErrorNT (node:internal/streams/destroy:151:8)
storefront:dev:       at emitErrorCloseNT (node:internal/streams/destroy:116:3)
storefront:dev:       at process.processTicksAndRejections (node:internal/process/task_queues:82:21) {
storefront:dev:     type: 'system',
storefront:dev:     errno: 'ECONNREFUSED',
storefront:dev:     code: 'ECONNREFUSED'
storefront:dev:   },
storefront:dev:   extraInfo: undefined,
storefront:dev:   page: '/[channel]/[locale]'
storefront:dev: }
```

### Steps to reproduce

1. Change the SALEOR_API_URL environment variable to ```http://localhost:8000/graphql/```

2. Run saleor with ```./manage.py runserver```

3. Run react-storefront with ```pnpm dev```

## System:
 - OS: Linux 6.0 Arch Linux
 - CPU: (4) x64 Intel(R) Core(TM) i5-4590 CPU @ 3.30GHz
 - Memory: 1.71 GB / 7.67 GB
 - Container: Yes
 - Shell: 5.9 - /bin/zsh
## Binaries:
 - Node: 18.13.0 - ~/.nvm/versions/node/v18.13.0/bin/node
 - Yarn: 1.22.19 - /usr/bin/yarn
 - npm: 9.4.0 - ~/.nvm/versions/node/v18.13.0/bin/npm
 - pnpm: 7.22.0
## Browsers:
 - Chromium: 107.0.5304.110
 - Firefox: 106.0.5

## Envirounment Varuables
- SALEOR_API_URL=http://localhost:8000/graphql/
- STOREFRONT_URL=http://localhost:3000
- CHECKOUT_APP_URL=http://localhost:3001
- CHECKOUT_STOREFRONT_URL=http://localhost:3001/checkout-spa/

**Comment by mmiszy** [comment]
When you open http://localhost:8000/graphql/ in your browser, do you see the GraphiQL editor?

**Comment by bsdelf** [comment]
I got same issue. The GraphQL query in browser works fine, admin dashboard works fine, but in storefront, when I click "Pay" button at checkout page, it does not have any respond, and the service log complains connection refused:

```
saleor-platform-api-1        | INFO:     172.20.0.1:42470 - "OPTIONS /graphql/ HTTP/1.1" 200 OK
saleor-app-checkout          | saleor-app-checkout:start: { 'req.headers.origin': undefined }
saleor-app-checkout          | saleor-app-checkout:start: ⚠ Warning! Auth token is not set. Make sure the app is installed in Saleor or set SALEOR_APP_TOKEN environment variable
saleor-app-checkout          | saleor-app-checkout:start: undefined [CombinedError: [Network] request to http://localhost:8000/graphql/ failed, reason: connect ECONNREFUSED 127.0.0.1:8000] {
saleor-app-checkout          | saleor-app-checkout:start:   graphQLErrors: [],
saleor-app-checkout          | saleor-app-checkout:start:   networkError: FetchError: request to http://localhost:8000/graphql/ failed, reason: connect ECONNREFUSED 127.0.0.1:8000
saleor-app-checkout          | saleor-app-checkout:start:       at ClientRequest.<anonymous> (/app/node_modules/.pnpm/next@12.3.1_6tziyx3dehkoeijunclpkpolha/node_modules/next/dist/compiled/node-fetch/index.js:1:65756)
saleor-app-checkout          | saleor-app-checkout:start:       at ClientRequest.emit (node:events:513:28)
saleor-app-checkout          | saleor-app-checkout:start:       at ClientRequest.emit (node:domain:489:12)
saleor-app-checkout          | saleor-app-checkout:start:       at Socket.socketErrorListener (node:_http_client:494:9)
saleor-app-checkout          | saleor-app-checkout:start:       at Socket.emit (node:events:513:28)
saleor-app-checkout          | saleor-app-checkout:start:       at Socket.emit (node:domain:489:12)
saleor-app-checkout          | saleor-app-checkout:start:       at emitErrorNT (node:internal/streams/destroy:157:8)
saleor-app-checkout          | saleor-app-checkout:start:       at emitErrorCloseNT (node:internal/streams/destroy:122:3)
saleor-app-checkout          | saleor-app-checkout:start:       at processTicksAndRejections (node:internal/process/task_queues:83:21) {
saleor-app-checkout          | saleor-app-checkout:start:     type: 'system',
saleor-app-checkout          | saleor-app-checkout:start:     errno: 'ECONNREFUSED',
saleor-app-checkout          | saleor-app-checkout:start:     code: 'ECONNREFUSED'
saleor-app-checkout          | saleor-app-checkout:start:   },
saleor-app-checkout          | saleor-app-checkout:start:   response: undefined
saleor-app-checkout          | saleor-app-checkout:start: }
saleor-app-checkout          | saleor-app-checkout:start: [CombinedError: [Network] request to http://localhost:8000/graphql/ failed, reason: connect ECONNREFUSED 127.0.0.1:8000] {
saleor-app-checkout          | saleor-app-checkout:start:   graphQLErrors: [],
saleor-app-checkout          | saleor-app-checkout:start:   networkError: FetchError: request to http://localhost:8000/graphql/ failed, reason: connect ECONNREFUSED 127.0.0.1:8000
saleor-app-checkout          | saleor-app-checkout:start:       at ClientRequest.<anonymous> (/app/node_modules/.pnpm/next@12.3.1_6tziyx3dehkoeijunclpkpolha/node_modules/next/dist/compiled/node-fetch/index.js:1:65756)
saleor-app-checkout          | saleor-app-checkout:start:       at ClientRequest.emit (node:events:513:28)
saleor-app-checkout          | saleor-app-checkout:start:       at ClientRequest.emit (node:domain:489:12)
saleor-app-checkout          | saleor-app-checkout:start:       at Socket.socketErrorListener (node:_http_client:494:9)
saleor-app-checkout          | saleor-app-checkout:start:       at Socket.emit (node:events:513:28)
saleor-app-checkout          | saleor-app-checkout:start:       at Socket.emit (node:domain:489:12)
saleor-app-checkout          | saleor-app-checkout:start:       at emitErrorNT (node:internal/streams/destroy:157:8)
saleor-app-checkout          | saleor-app-checkout:start:       at emitErrorCloseNT (node:internal/streams/destroy:122:3)
saleor-app-checkout          | saleor-app-checkout:start:       at processTicksAndRejections (node:internal/process/task_queues:83:21) {
saleor-app-checkout          | saleor-app-checkout:start:     type: 'system',
saleor-app-checkout          | saleor-app-checkout:start:     errno: 'ECONNREFUSED',
saleor-app-checkout          | saleor-app-checkout:start:     code: 'ECONNREFUSED'
saleor-app-checkout          | saleor-app-checkout:start:   },
saleor-app-checkout          | saleor-app-checkout:start:   response: undefined
saleor-app-checkout          | saleor-app-checkout:start: }
saleor-platform-api-1        | INFO:     172.20.0.1:42472 - "POST /graphql/ HTTP/1.1" 200 OK
saleor-platform-api-1        | INFO:     172.20.0.1:42470 - "POST /graphql/ HTTP/1.1" 200 OK
saleor-platform-api-1        | INFO:     172.20.0.1:42470 - "POST /graphql/ HTTP/1.1" 200 OK
saleor-platform-api-1        | INFO:     172.20.0.1:42470 - "POST /graphql/ HTTP/1.1" 200 OK
saleor-platform-api-1        | INFO:     172.20.0.1:42488 - "POST /graphql/ HTTP/1.1" 200 OK
saleor-platform-api-1        | INFO:     172.20.0.1:42488 - "POST /graphql/ HTTP/1.1" 200 OK
saleor-app-checkout          | saleor-app-checkout:start: { 'req.headers.origin': 'http://localhost:3000' }
saleor-app-checkout          | saleor-app-checkout:start: ⚠ Warning! Auth token is not set. Make sure the app is installed in Saleor or set SALEOR_APP_TOKEN environment variable
saleor-app-checkout          | saleor-app-checkout:start: { 'req.headers.origin': undefined }
saleor-app-checkout          | saleor-app-checkout:start: Q2hhbm5lbDox
saleor-app-checkout          | saleor-app-checkout:start: ⚠ Warning! Auth token is not set. Make sure the app is installed in Saleor or set SALEOR_APP_TOKEN environment variable
saleor-app-checkout          | saleor-app-checkout:start: [CombinedError: [Network] request to http://localhost:8000/graphql/ failed, reason: connect ECONNREFUSED 127.0.0.1:8000] {
saleor-app-checkout          | saleor-app-checkout:start:   graphQLErrors: [],
saleor-app-checkout          | saleor-app-checkout:start:   networkError: FetchError: request to http://localhost:8000/graphql/ failed, reason: connect ECONNREFUSED 127.0.0.1:8000
saleor-app-checkout          | saleor-app-checkout:start:       at ClientRequest.<anonymous> (/app/node_modules/.pnpm/next@12.3.1_6tziyx3dehkoeijunclpkpolha/node_modules/next/dist/compiled/node-fetch/index.js:1:65756)
saleor-app-checkout          | saleor-app-checkout:start:       at ClientRequest.emit (node:events:513:28)
saleor-app-checkout          | saleor-app-checkout:start:       at ClientRequest.emit (node:domain:489:12)
saleor-app-checkout          | saleor-app-checkout:start:       at Socket.socketErrorListener (node:_http_client:494:9)
saleor-app-checkout          | saleor-app-checkout:start:       at Socket.emit (node:events:513:28)
saleor-app-checkout          | saleor-app-checkout:start:       at Socket.emit (node:domain:489:12)
saleor-app-checkout          | saleor-app-checkout:start:       at emitErrorNT (node:internal/streams/destroy:157:8)
saleor-app-checkout          | saleor-app-checkout:start:       at emitErrorCloseNT (node:internal/streams/destroy:122:3)
saleor-app-checkout          | saleor-app-checkout:start:       at processTicksAndRejections (node:internal/process/task_queues:83:21) {
saleor-app-checkout          | saleor-app-checkout:start:     type: 'system',
saleor-app-checkout          | saleor-app-checkout:start:     errno: 'ECONNREFUSED',
saleor-app-checkout          | saleor-app-checkout:start:     code: 'ECONNREFUSED'
saleor-app-checkout          | saleor-app-checkout:start:   },
saleor-app-checkout          | saleor-app-checkout:start:   response: undefined
saleor-app-checkout          | saleor-app-checkout:start: }
saleor-app-checkout          | saleor-app-checkout:start: undefined [CombinedError: [Network] request to http://localhost:8000/graphql/ failed, reason: connect ECONNREFUSED 127.0.0.1:8000] {
saleor-app-checkout          | saleor-app-checkout:start:   graphQLErrors: [],
saleor-app-checkout          | saleor-app-checkout:start:   networkError: FetchError: request to http://localhost:8000/graphql/ failed, reason: connect ECONNREFUSED 127.0.0.1:8000
saleor-app-checkout          | saleor-app-checkout:start:       at ClientRequest.<anonymous> (/app/node_modules/.pnpm/next@12.3.1_6tziyx3dehkoeijunclpkpolha/node_modules/next/dist/compiled/node-fetch/index.js:1:65756)
saleor-app-checkout          | saleor-app-checkout:start:       at ClientRequest.emit (node:events:513:28)
saleor-app-checkout          | saleor-app-checkout:start:       at ClientRequest.emit (node:domain:489:12)
saleor-app-checkout          | saleor-app-checkout:start:       at Socket.socketErrorListener (node:_http_client:494:9)
saleor-app-checkout          | saleor-app-checkout:start:       at Socket.emit (node:events:513:28)
saleor-app-checkout          | saleor-app-checkout:start:       at Socket.emit (node:domain:489:12)
saleor-app-checkout          | saleor-app-checkout:start:       at emitErrorNT (node:internal/streams/destroy:157:8)
saleor-app-checkout          | saleor-app-checkout:start:       at emitErrorCloseNT (node:internal/streams/destroy:122:3)
saleor-app-checkout          | saleor-app-checkout:start:       at processTicksAndRejections (node:internal/process/task_queues:83:21) {
saleor-app-checkout          | saleor-app-checkout:start:     type: 'system',
saleor-app-checkout          | saleor-app-checkout:start:     errno: 'ECONNREFUSED',
saleor-app-checkout          | saleor-app-checkout:start:     code: 'ECONNREFUSED'
saleor-app-checkout          | saleor-app-checkout:start:   },
saleor-app-checkout          | saleor-app-checkout:start:   response: undefined
saleor-app-checkout          | saleor-app-checkout:start: }
saleor-app-checkout          | saleor-app-checkout:start: [CombinedError: [Network] request to http://localhost:8000/graphql/ failed, reason: connect ECONNREFUSED 127.0.0.1:8000] {
saleor-app-checkout          | saleor-app-checkout:start:   graphQLErrors: [],
saleor-app-checkout          | saleor-app-checkout:start:   networkError: FetchError: request to http://localhost:8000/graphql/ failed, reason: connect ECONNREFUSED 127.0.0.1:8000
saleor-app-checkout          | saleor-app-checkout:start:       at ClientRequest.<anonymous> (/app/node_modules/.pnpm/next@12.3.1_6tziyx3dehkoeijunclpkpolha/node_modules/next/dist/compiled/node-fetch/index.js:1:65756)
saleor-app-checkout          | saleor-app-checkout:start:       at ClientRequest.emit (node:events:513:28)
saleor-app-checkout          | saleor-app-checkout:start:       at ClientRequest.emit (node:domain:489:12)
saleor-app-checkout          | saleor-app-checkout:start:       at Socket.socketErrorListener (node:_http_client:494:9)
saleor-app-checkout          | saleor-app-checkout:start:       at Socket.emit (node:events:513:28)
saleor-app-checkout          | saleor-app-checkout:start:       at Socket.emit (node:domain:489:12)
saleor-app-checkout          | saleor-app-checkout:start:       at emitErrorNT (node:internal/streams/destroy:157:8)
saleor-app-checkout          | saleor-app-checkout:start:       at emitErrorCloseNT (node:internal/streams/destroy:122:3)
saleor-app-checkout          | saleor-app-checkout:start:       at processTicksAndRejections (node:internal/process/task_queues:83:21) {
saleor-app-checkout          | saleor-app-checkout:start:     type: 'system',
saleor-app-checkout          | saleor-app-checkout:start:     errno: 'ECONNREFUSED',
saleor-app-checkout          | saleor-app-checkout:start:     code: 'ECONNREFUSED'
saleor-app-checkout          | saleor-app-checkout:start:   },
saleor-app-checkout          | saleor-app-checkout:start:   response: undefined
saleor-app-checkout          | saleor-app-checkout:start: }
saleor-platform-api-1        | INFO:     172.20.0.1:42488 - "POST /graphql/ HTTP/1.1" 200 OK
saleor-app-checkout          | saleor-app-checkout:start: { 'req.headers.origin': 'http://localhost:3000' }
saleor-app-checkout          | saleor-app-checkout:start: ⚠ Warning! Auth token is not set. Make sure the app is installed in Saleor or set SALEOR_APP_TOKEN environment variable
saleor-app-checkout          | saleor-app-checkout:start: [CombinedError: [Network] request to http://localhost:8000/graphql/ failed, reason: connect ECONNREFUSED 127.0.0.1:8000] {
saleor-app-checkout          | saleor-app-checkout:start:   graphQLErrors: [],
saleor-app-checkout          | saleor-app-checkout:start:   networkError: FetchError: request to http://localhost:8000/graphql/ failed, reason: connect ECONNREFUSED 127.0.0.1:8000
saleor-app-checkout          | saleor-app-checkout:start:       at ClientRequest.<anonymous> (/app/node_modules/.pnpm/next@12.3.1_6tziyx3dehkoeijunclpkpolha/node_modules/next/dist/compiled/node-fetch/index.js:1:65756)
saleor-app-checkout          | saleor-app-checkout:start:       at ClientRequest.emit (node:events:513:28)
saleor-app-checkout          | saleor-app-checkout:start:       at ClientRequest.emit (node:domain:489:12)
saleor-app-checkout          | saleor-app-checkout:start:       at Socket.socketErrorListener (node:_http_client:494:9)
saleor-app-checkout          | saleor-app-checkout:start:       at Socket.emit (node:events:513:28)
saleor-app-checkout          | saleor-app-checkout:start:       at Socket.emit (node:domain:489:12)
saleor-app-checkout          | saleor-app-checkout:start:       at emitErrorNT (node:internal/streams/destroy:157:8)
saleor-app-checkout          | saleor-app-checkout:start:       at emitErrorCloseNT (node:internal/streams/destroy:122:3)
saleor-app-checkout          | saleor-app-checkout:start:       at processTicksAndRejections (node:internal/process/task_queues:83:21) {
saleor-app-checkout          | saleor-app-checkout:start:     type: 'system',
saleor-app-checkout          | saleor-app-checkout:start:     errno: 'ECONNREFUSED',
saleor-app-checkout          | saleor-app-checkout:start:     code: 'ECONNREFUSED'
saleor-app-checkout          | saleor-app-checkout:start:   },
saleor-app-checkout          | saleor-app-checkout:start:   response: undefined
saleor-app-checkout          | saleor-app-checkout:start: }
saleor-platform-api-1        | INFO:     172.20.0.1:42470 - "POST /graphql/ HTTP/1.1" 200 OK
saleor-platform-api-1        | INFO:     172.20.0.1:42490 - "POST /graphql/ HTTP/1.1" 200 OK
saleor-platform-api-1        | INFO:     172.20.0.1:42498 - "POST /graphql/ HTTP/1.1" 200 OK
saleor-platform-api-1        | INFO:     172.20.0.1:42498 - "POST /graphql/ HTTP/1.1" 200 OK
saleor-platform-api-1        | INFO:     172.20.0.1:42498 - "POST /graphql/ HTTP/1.1" 200 OK
saleor-app-checkout          | saleor-app-checkout:start: { 'req.headers.origin': 'http://localhost:3000' }
saleor-app-checkout          | saleor-app-checkout:start: ⚠ Warning! Auth token is not set. Make sure the app is installed in Saleor or set SALEOR_APP_TOKEN environment variable
saleor-app-checkout          | saleor-app-checkout:start: [CombinedError: [Network] request to http://localhost:8000/graphql/ failed, reason: connect ECONNREFUSED 127.0.0.1:8000] {
saleor-app-checkout          | saleor-app-checkout:start:   graphQLErrors: [],
saleor-app-checkout          | saleor-app-checkout:start:   networkError: FetchError: request to http://localhost:8000/graphql/ failed, reason: connect ECONNREFUSED 127.0.0.1:8000
saleor-app-checkout          | saleor-app-checkout:start:       at ClientRequest.<anonymous> (/app/node_modules/.pnpm/next@12.3.1_6tziyx3dehkoeijunclpkpolha/node_modules/next/dist/compiled/node-fetch/index.js:1:65756)
saleor-app-checkout          | saleor-app-checkout:start:       at ClientRequest.emit (node:events:513:28)
saleor-app-checkout          | saleor-app-checkout:start:       at ClientRequest.emit (node:domain:489:12)
saleor-app-checkout          | saleor-app-checkout:start:       at Socket.socketErrorListener (node:_http_client:494:9)
saleor-app-checkout          | saleor-app-checkout:start:       at Socket.emit (node:events:513:28)
saleor-app-checkout          | saleor-app-checkout:start:       at Socket.emit (node:domain:489:12)
saleor-app-checkout          | saleor-app-checkout:start:       at emitErrorNT (node:internal/streams/destroy:157:8)
saleor-app-checkout          | saleor-app-checkout:start:       at emitErrorCloseNT (node:internal/streams/destroy:122:3)
saleor-app-checkout          | saleor-app-checkout:start:       at processTicksAndRejections (node:internal/process/task_queues:83:21) {
saleor-app-checkout          | saleor-app-checkout:start:     type: 'system',
saleor-app-checkout          | saleor-app-checkout:start:     errno: 'ECONNREFUSED',
saleor-app-checkout          | saleor-app-checkout:start:     code: 'ECONNREFUSED'
saleor-app-checkout          | saleor-app-checkout:start:   },
saleor-app-checkout          | saleor-app-checkout:start:   response: undefined
saleor-app-checkout          | saleor-app-checkout:start: }
```

My local setup is followed by readme instructions https://github.com/saleor/saleor-platform#how-to-run-it.

- OS: Void Linux 
- Kernel version: 6.1.12_1
- docker compose version: v2.16.0
- saleor-platform git commit: c3406d1024a9973602d4b5193420568cc71325e0

**Comment by omarghader** [comment]
I have the same issue, I saw that the checkout should have a token to communicate with the backend.
However, i don't see how to create a token.

Please any help is appreaciated really ! :sos:

**Comment by fedexin40** [comment]
Not sure this is exacting the same problem I faced, but I shared my experience when starting the project
The issue is because react-storefront and saleor-platform are in different docker projects

By default docker creates a network for each project (docker-compose.yml) that's why each service listed in the file docker-compose.yml can communicate each other

You can find more information about this in docker documentation but basically what you need to do is to add both projects into the same network

**Extract from docker-compose in react-storefront project** 

``` 
.
.
.
storefront:
    container_name: storefront
    build:
      context: .
      dockerfile: Dockerfile.base
      args:
        - SALEOR_API_URL=http://localhost:8000/graphql/ # handled by nginx
        - STOREFRONT_URL=http://localhost:3000
        - CHECKOUT_APP_URL=http://localhost:3001
        - CHECKOUT_STOREFRONT_URL=http://localhost:3001/checkout-spa/
        - CLOUD_DEPLOYMENT_URL=
    ports:
      - 3000:3000
    networks:
      - saleor
    command: sh -c '(nginx &) && pnpm turbo run start --filter=storefront...'

networks:
  saleor:
    external: true
```

And the same needs to be added in the saleor-platform project

```
.
.
.
mailhog:
    image: mailhog/mailhog
    ports:
      - 1025:1025 # smtp server
      - 8025:8025 # web ui. Visit http://localhost:8025/ to check emails
    restart: unless-stopped
    networks:
      - saleor

volumes:
  saleor-db:
    driver: local
  saleor-redis:
    driver: local
  saleor-media:

networks:
  saleor:
    external: true
```

Other important change that you need to take is the below part inside docker-compose.yml in saleor-platform proyect

```
services:
  api:
    image: ghcr.io/saleor/saleor:3.12.5
    ports:
      - 8000:8000
    restart: unless-stopped
    networks:
      - saleor
    stdin_open: true
    tty: true
    depends_on:
      - db
      - redis
      - jaeger
    volumes:
      # shared volume between worker and api for media
      - saleor-media:/app/media
    env_file:
      - common.env
      - backend.env
    environment:
      - JAEGER_AGENT_HOST=jaeger
      - DASHBOARD_URL=http://localhost:9000/
      - ALLOWED_HOSTS=*
```

The last time is allowed_hosts this comes from Django, the framework that is used to build the saleor core, I used a start to allow all connections, which is not recommended but you need to add your store service there

**Comment by ace-han** [comment]
@dotwilliamrc When I change node to version `16.*` everything works like a charm

```shell
➜  react-storefront git:(main) ✗ nvm use 16
Now using node v16.17.0 (npm v8.15.0)
➜  react-storefront git:(main) ✗ node -v
v16.17.0
➜  react-storefront git:(main) ✗ pnpm dev
... It should work ...
```

**Comment by jukafah** [comment]
Can confirm switching to node v16 fixes this issue. I burnt a bit of time on it as well.

**Comment by mmiszy** [comment]
Closing due to lack of response.
